apiVersion: v1
kind: Service
metadata:
  name: crashy-mccrashface-app-service
  namespace: production
spec:
  selector:
    app: crashy-mccrashface-app-service
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8081