apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: crashy-mccrashface-app-service
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  type: NodePort
  selector:
    app: crashy-mccrashface-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: production
  name: crashy-mccrashface-app-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: crashy-mccrashface-app-service
              port:
                number: 80