on: push
name: Docker Image CI

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      #run: |
      #  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      run: echo ${DOCKER_PASSWORD} | docker login --username "$DOCKER_USER" --password-stdin
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
      run: docker build . --file Dockerfile --tag ${DOCKER_USER}/crashy-mccrashface:${GITHUB_RUN_ID}
      
    - name: Docker Push
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
      run: |
        docker images
        docker push ${DOCKER_USER}/crashy-mccrashface:${GITHUB_RUN_ID}